baseurl:            /peel

highlighter:        rouge

title:              Peel Framework

current_version:    1.1.4

collections:
  manual:
    output:         true
  repository:
    output:         true
  legal:
    output:         true
